Country.create([
  { :fullname => "(please select a country)", :abbreviation => "  " },
  { :abbreviation => "AF", :fullname => "Afghanistan" }, 
  { :abbreviation => "AL", :fullname => "Albania" }, 
  { :abbreviation => "DZ", :fullname => "Algeria" }, 
  { :abbreviation => "AS", :fullname => "American Samoa" }, 
  { :abbreviation => "AD", :fullname => "Andorra" }, 
  { :abbreviation => "AO", :fullname => "Angola" }, 
  { :abbreviation => "AI", :fullname => "Anguilla" }, 
  { :abbreviation => "AQ", :fullname => "Antarctica" }, 
  { :abbreviation => "AG", :fullname => "Antigua and Barbuda" }, 
  { :abbreviation => "AR", :fullname => "Argentina" }, 
  { :abbreviation => "AM", :fullname => "Armenia" }, 
  { :abbreviation => "AW", :fullname => "Aruba" }, 
  { :abbreviation => "AU", :fullname => "Australia" }, 
  { :abbreviation => "AT", :fullname => "Austria" }, 
  { :abbreviation => "AZ", :fullname => "Azerbaijan" }, 
  { :abbreviation => "BS", :fullname => "Bahamas" }, 
  { :abbreviation => "BH", :fullname => "Bahrain" }, 
  { :abbreviation => "BD", :fullname => "Bangladesh" }, 
  { :abbreviation => "BB", :fullname => "Barbados" }, 
  { :abbreviation => "BY", :fullname => "Belarus" }, 
  { :abbreviation => "BE", :fullname => "Belgium" }, 
  { :abbreviation => "BZ", :fullname => "Belize" }, 
  { :abbreviation => "BJ", :fullname => "Benin" }, 
  { :abbreviation => "BM", :fullname => "Bermuda" }, 
  { :abbreviation => "BT", :fullname => "Bhutan" }, 
  { :abbreviation => "BO", :fullname => "Bolivia" }, 
  { :abbreviation => "BA", :fullname => "Bosnia and Herzegowina" }, 
  { :abbreviation => "BW", :fullname => "Botswana" }, 
  { :abbreviation => "BV", :fullname => "Bouvet Island" }, 
  { :abbreviation => "BR", :fullname => "Brazil" }, 
  { :abbreviation => "IO", :fullname => "British Indian Ocean Territory" }, 
  { :abbreviation => "BN", :fullname => "Brunei Darussalam" }, 
  { :abbreviation => "BG", :fullname => "Bulgaria" }, 
  { :abbreviation => "BF", :fullname => "Burkina Faso" }, 
  { :abbreviation => "BI", :fullname => "Burundi" }, 
  { :abbreviation => "KH", :fullname => "Cambodia" }, 
  { :abbreviation => "CM", :fullname => "Cameroon" }, 
  { :abbreviation => "CA", :fullname => "Canada" }, 
  { :abbreviation => "CV", :fullname => "Cape Verde" }, 
  { :abbreviation => "KY", :fullname => "Cayman Islands" }, 
  { :abbreviation => "CF", :fullname => "Central African Republic" }, 
  { :abbreviation => "TD", :fullname => "Chad" }, 
  { :abbreviation => "CL", :fullname => "Chile" }, 
  { :abbreviation => "CN", :fullname => "China" }, 
  { :abbreviation => "CX", :fullname => "Christmas Island" }, 
  { :abbreviation => "CC", :fullname => "Cocos (Keeling) Islands" }, 
  { :abbreviation => "CO", :fullname => "Colombia" }, 
  { :abbreviation => "KM", :fullname => "Comoros" }, 
  { :abbreviation => "CG", :fullname => "Congo" }, 
  { :abbreviation => "CD", :fullname => "Congo, the Democratic Republic of the" }, 
  { :abbreviation => "CK", :fullname => "Cook Islands" }, 
  { :abbreviation => "CR", :fullname => "Costa Rica" }, 
  { :abbreviation => "CI", :fullname => "Cote d'Ivoire" }, 
  { :abbreviation => "HR", :fullname => "Croatia (Hrvatska)" }, 
  { :abbreviation => "CU", :fullname => "Cuba" }, 
  { :abbreviation => "CY", :fullname => "Cyprus" }, 
  { :abbreviation => "CZ", :fullname => "Czech Republic" }, 
  { :abbreviation => "DK", :fullname => "Denmark" }, 
  { :abbreviation => "DJ", :fullname => "Djibouti" }, 
  { :abbreviation => "DM", :fullname => "Dominica" }, 
  { :abbreviation => "DO", :fullname => "Dominican Republic" }, 
  { :abbreviation => "TP", :fullname => "East Timor" }, 
  { :abbreviation => "EC", :fullname => "Ecuador" }, 
  { :abbreviation => "EG", :fullname => "Egypt" }, 
  { :abbreviation => "SV", :fullname => "El Salvador" }, 
  { :abbreviation => "GQ", :fullname => "Equatorial Guinea" }, 
  { :abbreviation => "ER", :fullname => "Eritrea" }, 
  { :abbreviation => "EE", :fullname => "Estonia" }, 
  { :abbreviation => "ET", :fullname => "Ethiopia" }, 
  { :abbreviation => "FK", :fullname => "Falkland Islands (Malvinas)" }, 
  { :abbreviation => "FO", :fullname => "Faroe Islands" }, 
  { :abbreviation => "FJ", :fullname => "Fiji" }, 
  { :abbreviation => "FI", :fullname => "Finland" }, 
  { :abbreviation => "FR", :fullname => "France" }, 
  { :abbreviation => "FX", :fullname => "France, Metropolitan" }, 
  { :abbreviation => "GF", :fullname => "French Guiana" }, 
  { :abbreviation => "PF", :fullname => "French Polynesia" }, 
  { :abbreviation => "TF", :fullname => "French Southern Territories" }, 
  { :abbreviation => "GA", :fullname => "Gabon" }, 
  { :abbreviation => "GM", :fullname => "Gambia" }, 
  { :abbreviation => "GE", :fullname => "Georgia" }, 
  { :abbreviation => "DE", :fullname => "Germany" }, 
  { :abbreviation => "GH", :fullname => "Ghana" }, 
  { :abbreviation => "GI", :fullname => "Gibraltar" }, 
  { :abbreviation => "GR", :fullname => "Greece" }, 
  { :abbreviation => "GL", :fullname => "Greenland" }, 
  { :abbreviation => "GD", :fullname => "Grenada" }, 
  { :abbreviation => "GP", :fullname => "Guadeloupe" }, 
  { :abbreviation => "GU", :fullname => "Guam" }, 
  { :abbreviation => "GT", :fullname => "Guatemala" }, 
  { :abbreviation => "GN", :fullname => "Guinea" }, 
  { :abbreviation => "GW", :fullname => "Guinea-Bissau" }, 
  { :abbreviation => "GY", :fullname => "Guyana" }, 
  { :abbreviation => "HT", :fullname => "Haiti" }, 
  { :abbreviation => "HM", :fullname => "Heard and Mc Donald Islands" }, 
  { :abbreviation => "VA", :fullname => "Holy See (Vatican City State)" }, 
  { :abbreviation => "HN", :fullname => "Honduras" }, 
  { :abbreviation => "HK", :fullname => "Hong Kong" }, 
  { :abbreviation => "HU", :fullname => "Hungary" }, 
  { :abbreviation => "IS", :fullname => "Iceland" }, 
  { :abbreviation => "IN", :fullname => "India" }, 
  { :abbreviation => "ID", :fullname => "Indonesia" }, 
  { :abbreviation => "IR", :fullname => "Iran (Islamic Republic of)" }, 
  { :abbreviation => "IQ", :fullname => "Iraq" }, 
  { :abbreviation => "IE", :fullname => "Ireland" }, 
  { :abbreviation => "IL", :fullname => "Israel" }, 
  { :abbreviation => "IT", :fullname => "Italy" }, 
  { :abbreviation => "JM", :fullname => "Jamaica" }, 
  { :abbreviation => "JP", :fullname => "Japan" }, 
  { :abbreviation => "JO", :fullname => "Jordan" }, 
  { :abbreviation => "KZ", :fullname => "Kazakhstan" }, 
  { :abbreviation => "KE", :fullname => "Kenya" }, 
  { :abbreviation => "KI", :fullname => "Kiribati" }, 
  { :abbreviation => "KP", :fullname => "Korea, Democratic People's Republic of" }, 
  { :abbreviation => "KR", :fullname => "Korea, Republic of" }, 
  { :abbreviation => "KW", :fullname => "Kuwait" }, 
  { :abbreviation => "KG", :fullname => "Kyrgyzstan" }, 
  { :abbreviation => "LA", :fullname => "Lao People's Democratic Republic" }, 
  { :abbreviation => "LV", :fullname => "Latvia" }, 
  { :abbreviation => "LB", :fullname => "Lebanon" }, 
  { :abbreviation => "LS", :fullname => "Lesotho" }, 
  { :abbreviation => "LR", :fullname => "Liberia" }, 
  { :abbreviation => "LY", :fullname => "Libyan Arab Jamahiriya" }, 
  { :abbreviation => "LI", :fullname => "Liechtenstein" }, 
  { :abbreviation => "LT", :fullname => "Lithuania" }, 
  { :abbreviation => "LU", :fullname => "Luxembourg" }, 
  { :abbreviation => "MO", :fullname => "Macau" }, 
  { :abbreviation => "MK", :fullname => "Macedonia, The Former Yugoslav Republic of" }, 
  { :abbreviation => "MG", :fullname => "Madagascar" }, 
  { :abbreviation => "MW", :fullname => "Malawi" }, 
  { :abbreviation => "MY", :fullname => "Malaysia" }, 
  { :abbreviation => "MV", :fullname => "Maldives" }, 
  { :abbreviation => "ML", :fullname => "Mali" }, 
  { :abbreviation => "MT", :fullname => "Malta" }, 
  { :abbreviation => "MH", :fullname => "Marshall Islands" }, 
  { :abbreviation => "MQ", :fullname => "Martinique" }, 
  { :abbreviation => "MR", :fullname => "Mauritania" }, 
  { :abbreviation => "MU", :fullname => "Mauritius" }, 
  { :abbreviation => "YT", :fullname => "Mayotte" }, 
  { :abbreviation => "MX", :fullname => "Mexico" }, 
  { :abbreviation => "FM", :fullname => "Micronesia, Federated States of" }, 
  { :abbreviation => "MD", :fullname => "Moldova, Republic of" }, 
  { :abbreviation => "MC", :fullname => "Monaco" }, 
  { :abbreviation => "MN", :fullname => "Mongolia" }, 
  { :abbreviation => "MS", :fullname => "Montserrat" }, 
  { :abbreviation => "MA", :fullname => "Morocco" }, 
  { :abbreviation => "MZ", :fullname => "Mozambique" }, 
  { :abbreviation => "MM", :fullname => "Myanmar" }, 
  { :abbreviation => "NA", :fullname => "Namibia" }, 
  { :abbreviation => "NR", :fullname => "Nauru" }, 
  { :abbreviation => "NP", :fullname => "Nepal" }, 
  { :abbreviation => "NL", :fullname => "Netherlands" }, 
  { :abbreviation => "AN", :fullname => "Netherlands Antilles" }, 
  { :abbreviation => "NC", :fullname => "New Caledonia" }, 
  { :abbreviation => "NZ", :fullname => "New Zealand" }, 
  { :abbreviation => "NI", :fullname => "Nicaragua" }, 
  { :abbreviation => "NE", :fullname => "Niger" }, 
  { :abbreviation => "NG", :fullname => "Nigeria" }, 
  { :abbreviation => "NU", :fullname => "Niue" }, 
  { :abbreviation => "NF", :fullname => "Norfolk Island" }, 
  { :abbreviation => "MP", :fullname => "Northern Mariana Islands" }, 
  { :abbreviation => "NO", :fullname => "Norway" }, 
  { :abbreviation => "OM", :fullname => "Oman" }, 
  { :abbreviation => "PK", :fullname => "Pakistan" }, 
  { :abbreviation => "PW", :fullname => "Palau" }, 
  { :abbreviation => "PA", :fullname => "Panama" }, 
  { :abbreviation => "PG", :fullname => "Papua New Guinea" }, 
  { :abbreviation => "PY", :fullname => "Paraguay" }, 
  { :abbreviation => "PE", :fullname => "Peru" }, 
  { :abbreviation => "PH", :fullname => "Philippines" }, 
  { :abbreviation => "PN", :fullname => "Pitcairn" }, 
  { :abbreviation => "PL", :fullname => "Poland" }, 
  { :abbreviation => "PT", :fullname => "Portugal" }, 
  { :abbreviation => "PR", :fullname => "Puerto Rico" }, 
  { :abbreviation => "QA", :fullname => "Qatar" }, 
  { :abbreviation => "RE", :fullname => "Reunion" }, 
  { :abbreviation => "RO", :fullname => "Romania" }, 
  { :abbreviation => "RU", :fullname => "Russian Federation" }, 
  { :abbreviation => "RW", :fullname => "Rwanda" }, 
  { :abbreviation => "KN", :fullname => "Saint Kitts and Nevis" }, 
  { :abbreviation => "LC", :fullname => "Saint LUCIA" }, 
  { :abbreviation => "VC", :fullname => "Saint Vincent and the Grenadines" }, 
  { :abbreviation => "WS", :fullname => "Samoa" }, 
  { :abbreviation => "SM", :fullname => "San Marino" }, 
  { :abbreviation => "ST", :fullname => "Sao Tome and Principe" }, 
  { :abbreviation => "SA", :fullname => "Saudi Arabia" }, 
  { :abbreviation => "SN", :fullname => "Senegal" }, 
  { :abbreviation => "SC", :fullname => "Seychelles" }, 
  { :abbreviation => "SL", :fullname => "Sierra Leone" }, 
  { :abbreviation => "SG", :fullname => "Singapore" }, 
  { :abbreviation => "SK", :fullname => "Slovakia (Slovak Republic)" }, 
  { :abbreviation => "SI", :fullname => "Slovenia" }, 
  { :abbreviation => "SB", :fullname => "Solomon Islands" }, 
  { :abbreviation => "SO", :fullname => "Somalia" }, 
  { :abbreviation => "ZA", :fullname => "South Africa" }, 
  { :abbreviation => "GS", :fullname => "South Georgia and the South Sandwich Islands" }, 
  { :abbreviation => "ES", :fullname => "Spain" }, 
  { :abbreviation => "LK", :fullname => "Sri Lanka" }, 
  { :abbreviation => "SH", :fullname => "St. Helena" }, 
  { :abbreviation => "PM", :fullname => "St. Pierre and Miquelon" }, 
  { :abbreviation => "SD", :fullname => "Sudan" }, 
  { :abbreviation => "SR", :fullname => "Suriname" }, 
  { :abbreviation => "SJ", :fullname => "Svalbard and Jan Mayen Islands" }, 
  { :abbreviation => "SZ", :fullname => "Swaziland" }, 
  { :abbreviation => "SE", :fullname => "Sweden" }, 
  { :abbreviation => "CH", :fullname => "Switzerland" }, 
  { :abbreviation => "SY", :fullname => "Syrian Arab Republic" }, 
  { :abbreviation => "TW", :fullname => "Taiwan, Province of China" }, 
  { :abbreviation => "TJ", :fullname => "Tajikistan" }, 
  { :abbreviation => "TZ", :fullname => "Tanzania, United Republic of" }, 
  { :abbreviation => "TH", :fullname => "Thailand" }, 
  { :abbreviation => "TG", :fullname => "Togo" }, 
  { :abbreviation => "TK", :fullname => "Tokelau" }, 
  { :abbreviation => "TO", :fullname => "Tonga" }, 
  { :abbreviation => "TT", :fullname => "Trinidad and Tobago" }, 
  { :abbreviation => "TN", :fullname => "Tunisia" }, 
  { :abbreviation => "TR", :fullname => "Turkey" }, 
  { :abbreviation => "TM", :fullname => "Turkmenistan" }, 
  { :abbreviation => "TC", :fullname => "Turks and Caicos Islands" }, 
  { :abbreviation => "TV", :fullname => "Tuvalu" }, 
  { :abbreviation => "UG", :fullname => "Uganda" }, 
  { :abbreviation => "UA", :fullname => "Ukraine" }, 
  { :abbreviation => "AE", :fullname => "United Arab Emirates" }, 
  { :abbreviation => "GB", :fullname => "United Kingdom" }, 
  { :abbreviation => "US", :fullname => "United States" }, 
  { :abbreviation => "UM", :fullname => "United States Minor Outlying Islands" }, 
  { :abbreviation => "UY", :fullname => "Uruguay" }, 
  { :abbreviation => "UZ", :fullname => "Uzbekistan" }, 
  { :abbreviation => "VU", :fullname => "Vanuatu" }, 
  { :abbreviation => "VE", :fullname => "Venezuela" }, 
  { :abbreviation => "VN", :fullname => "Viet Nam" }, 
  { :abbreviation => "VG", :fullname => "Virgin Islands (British)" }, 
  { :abbreviation => "VI", :fullname => "Virgin Islands (U.S.)" }, 
  { :abbreviation => "WF", :fullname => "Wallis and Futuna Islands" }, 
  { :abbreviation => "EH", :fullname => "Western Sahara" }, 
  { :abbreviation => "YE", :fullname => "Yemen" }, 
  { :abbreviation => "YU", :fullname => "Yugoslavia" }, 
  { :abbreviation => "ZM", :fullname => "Zambia" }, 
  { :abbreviation => "ZW", :fullname => "Zimbabwe" }, 
  { :abbreviation => "FU", :fullname => "Fu** you! You don't need to know!" }
])
